language: node_js
node_js:
  - "0.10.25"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - gulp test
  - gulp build
sudo: false
after_success:
  - gulp coveralls
