language: node_js
node_js:
- 0.10.25
install:
- npm install -g gulp
- npm install -g bower
- npm install
- bower install
before_script:
- gulp test
script:
- gulp clean
- gulp preprocessors
- gulp useref
- gulp copy-files
- gulp optimize-build
- gulp finger-print
- gulp finger-print-replace
- gulp aws-publish
sudo: false
env:
  global:
  - AWS_BUCKET=work.topcoder-dev.com
  - AWS_REGION=us-east-1
  - AWS_CDN_URL=//work.topcoder-dev.com
  - BASE_URL=/work/
  - AUTH0_DOMAIN=topcoder-domain.auth0.com
  - BASE_API_URL=https://api.topcoder-dev.com/v3/
  - NEWRELIC_APPLICATION_ID=7374849
  - NEWRELIC_LICENSE_KEY=496af5ee90
  - API_URL=https://api.topcoder-dev.com/v3
  - API_URL_V2=https://api.topcoder-dev.com/v2
  - AVATAR_URL=http://www.topcoder.com
  - SUBMISSION_URL=https://studio.topcoder.com
  - secure: ALEXBpbPpCsUddsvz43GCHdKZpAVeN6pF4BV6Li/L8CviF4tT089fRHSc6VKSR2iLyNGPn+Sfmh7TSQ8+dBNL7xvbcZSE9v4qqx/6KMqTamLdf6gRwopirRZULgXr6Itg1o2+bQBu9xZKKQLMA2lJIasFADB9xIpXZLVn6U09Ztb/2I=
  - secure: a3MImI1SYRMi+H/RAL7NWFBKbLtZwQiRWhHieW5ZklSN2xK5+pwE6JRpJHvDBk6EdXO2ZDmVGfWsXrGXPmVxYx4Sc6vnIDGlVnZBFzHm7EmnmDV2yjtHO/PBoMm2vEdWS5QmTy37arUdVNN/aZKm6YR8Vlo7jYkAE9bWxvhbiSg=
  - secure: PESHEn26LQ3mn8E8twqvMb0lbbyzoznlID8TSQyWRdOAcWAnEsq29FOoYR4Lfbmy+nPzytQfTh6GY0cxou8TORshHwh2tD3cAbKhAf2OrNX1OHXeKCvFu3petbRJmYFgHNgr+Drc5LSF0zcwd6b50DkLtzZqG5GtxAfvEfypdQc=
