language: node_js
node_js:
  - "0.10.25"
before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
script:
  - gulp build
sudo: false
env:
  global:
    - AWS_BUCKET=foo
    - AWS_KEY=foo
    - AWS_REGION=bar
    - AWS_SECRET=bar
    - AWS_CDN_URL=
    - VERSION=1
    - USE_STUBS=true
    - AUTH0_CLIENT_ID=Auth0_Client_Id
    - AUTH0_DOMAIN=topcoder-domain.auth0.com
    - RET_URL=login_return_url
    - CALLBACK_URL=login_callback_url
    - NEWRELIC_APPLICATION_ID=7374849
    - NEWRELIC_LICENSE_KEY=496af5ee90

after_success:
  - gulp coveralls


