language: node_js
node_js:
- 5.10.1
install:
- npm install
script:
- webpack -p --bail --progress --build
sudo: false
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: connect.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: connect.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: connect.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  # DEV_AWS_KEY
  - secure: IGH+DO66U82cyb4pVitHYcb+IRfLLVJGV3YX0ie3JAAAJH2wl4N9oi+zd2hr9xHTD511G05bexi+WU/v9XA6kh3EcXyGh9ohNuve44R2j70L1g/EN297bTnipBKdARPvX1G5D6qXIZMRh4ls22wyB+oA6akm5FnHRWlDryARIgc=
  # DEV_AWS_SECRET
  - secure: oC0qonshTKmgAOxwzFy/dAWJXloDuuKlz7pDtzbHkvcguqWVKu3vCEqkxFESzlMdPsoujWu7QBZDJCW7+EHAsGq8Ydu75fwiWRmeX8lI6x6JGcYLAgocrpfQTbU51lKQhv4A8tdJ1k5d7ZyUTXWjmgCCbPL3rFj+6h1X4I95oQA=
  # QA_AWS_KEY
  - secure: lpdUndFkKU1MbQZ7pT7ke4XWItHNYCDSt8vInYqiBHByK42//DzUoUQhP3B8QVf8teKBnXnbbJGl01SpUgd1+ZdepI1ksa06KOfeyRrZ3cmFh3UBR5RWDYmxZxnJFgzmL3tMTEfzImO2Khd0CLIdIOAwhRXtI2Z5Ipwqnu295X8=
  # QA_AWS_SECRET
  - secure: aIuFS/dIGZbWIBUNRrw1d1Z/RJHIafYTyNerx6QWo/ENsZyBKC2FlD1pFXd9AZkyYuF99wZxgKsBoiYpTraLdJ26K4YQYQIRw/5HsWYZqukI8yctsZ6NdvZkXKncZbMlW5KJADUGHHa+ktzmqXlwS0qO00HlSaTwHCr15XKoS/M=
  # MASTER_AWS_KEY
  - secure: gpEtWMYBfF8NvC+nfLKw6OtONISssGMyzJ7qyXPIviaaRasnVD9nArlEozBw/qrhcYA0TPFMg7ZQq5NipkOIw2RZUgEtpKHD+hmaO7/apE3RtX85QY44wFat/VydQWl2U9EodS9XcdsKEDSghgnehbB0mO6piuvnC6reQwo1Z/0=
  # MASTER_AWS_SECRET
  - secure: Oxu8D8CFk6EDLi/RPXRM3Peb0SVzVWApz3IKvROXWD8IbOfVBgvyaOdhhh2q10V085kkcAMayYNSifRd4ZhpTOJdQF/UoaczFIekhNDq/zPZLEf9j/EgJD9oWGkgIP9ct3KWSphtUChcNTvNHAlC+4kGMo3djZBe/BCkgyiwlZE=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
